from __future__ import absolute_import
from __future__ import print_function
# -*- coding: utf-8 -*-

from pyth.plugins.xhtml.reader import XHTMLReader
from pyth.plugins.xhtml.writer import XHTMLWriter
from pyth.plugins.rtf15.writer import Rtf15Writer
import xhtml

from six import StringIO

# A simple xhtml document with limited features.
content = StringIO(r"""
  <div>
  <p><strong><ins>Hello World </ins></strong></p> <p></p> <p>This is is a test for HTML to RTF&nbsp;</p> <p></p> <ul> <li dir = "auto">List item 1</li> <li dir = "auto">List item 2</li> <ul> <li dir = "auto">Sub List Item 1</li> <li dir = "auto">SubList Item 2</li> <li dir = "auto">SubList Item 3</li></ul>
  <li dir = "auto">List Item 3</li> </ul>
  <p></p>
  <p></p>
  <p></p>
  </div>
""")

css = """
  .important {font-weight: bold}
  p.bold {font-weight: bold}
  .other {font-weight: normal; color: blue}
"""


def write_rtf_file(filename, bytescontent, print_msg=True):
    """
    Helper function for testing etc.
    Wraps the HTML fragment generated by the Writer in a complete document.
    Writes that document to a file.
    """
    with open(filename, "wb") as out:
        out.write(str.encode(bytescontent))
    if print_msg:
        print("##### wrote HTML to RTF Content", bytescontent)
        print("##### wrote HTML to RTF to", filename)


if __name__ == '__main__':
    doc = XHTMLReader.read(content, css)
    write_rtf_file(filename="sample.rtf", bytescontent=Rtf15Writer.write(
        doc).getvalue(), print_msg=True)
